### ISSUE TITLE
A bug in set(and add) function from the Sushiswap due to lossing profit of users

### ISSUE THREAD

**Issue by LiRiu** [swappidex/swappi-farm#4]
## **Bug Description**

the _withUpdate in set and add function being an optional flag is irresponsible and possibly malicious.

( same vulnerability occured in [milkyswap](https://github.com/milkyswap/milkyswap/commit/00a09c6121bb57301f200658ebd104de0a3125f5) and OTHER SUSHISWAP LIKE...

the reason is below: The set(or add) function will change the allocPoint/totalAllocPoint of the pool

```
    // Add a new lp to the pool. Can only be called by the whitelist admin.
    function add(
        uint256 _allocPoint,
        IERC20 _token,
        uint256 _startTime,
        bool _withUpdate
    ) external onlyWhitelistAdmin {
        if (_withUpdate) {
            massUpdatePools();
        }
        if (_startTime < block.timestamp) _startTime = block.timestamp;
        totalAllocPoint = totalAllocPoint + _allocPoint;
        poolInfo.push(
            PoolInfo({
                token: _token,
                allocPoint: _allocPoint,
                lastRewardTime: _startTime,
                totalSupply: 0,
                workingSupply: 0,
                accRewardPerShare: 0
            })
        );
    }

    // Update the given pool's reward allocation point. Can only be called by the owner.
    function set(
        uint256 _pid,
        uint256 _allocPoint,
        bool _withUpdate
    ) external onlyWhitelistAdmin {
        if (_withUpdate) {
            massUpdatePools();
        }
        uint256 prevAllocPoint = poolInfo[_pid].allocPoint;
        poolInfo[_pid].allocPoint = _allocPoint;
        if (prevAllocPoint != _allocPoint) {
            totalAllocPoint = totalAllocPoint - prevAllocPoint + _allocPoint;
        }
    }

```

so that, If a increase allocPoint set invoke occurs in a farming period, the user's reward should be affected as follows.

farming reward without set function: ![](https://bafybeietptlpka2jbr2pawzor5svzhr3dp7pej7aoajilmzhjyi226zfxe.ipfs.dweb.link/IMG_4DB041E0212D-1.jpeg)

farming reward with set function ( withUpdate == True ): ![](https://bafybeid2bkeuahlmf6xytlsldoah6ncmaznzmejthv2gcwblxgpljev7ki.ipfs.dweb.link/IMG_CB67B6723412-1.jpeg)

farming reward with set function ( withUpdate == False ): ![](https://bafybeiajai3yqcygtfxsd2xoxrfjruzgjbrcaetsvtqsijqcf4muyfctie.ipfs.dweb.link/IMG_EC5E5CBAEEB3-1.jpeg)

the userReward3 > userReward2

It can be seen that if the admin calls the increase set function in a farming period, the user's income will increase unexpectedly. The extra part will be the loss of other pools' users.

## **Impact**

Users' rewards will increase or decrease unexpectedly.

## **Recommendation**

del the _withUpdate option, or set it always true.

code modify like [this commit](https://github.com/milkyswap/milkyswap/commit/00a09c6121bb57301f200658ebd104de0a3125f5)

## **References**
**[milkyswap same vulnerability fixed](https://github.com/milkyswap/milkyswap/commit/00a09c6121bb57301f200658ebd104de0a3125f5)**

**[https://draculaprotocol.medium.com/sushiswap-smart-contract-bug-and-quality-of-audits-in-community-f50ee0545bc6](https://draculaprotocol.medium.com/sushiswap-smart-contract-bug-and-quality-of-audits-in-community-f50ee0545bc6)**

**Comment by posaggen** [comment]
The _withUpdate option cannot be removed because the gas cost of massUpdatePools() is proportional to the number of farming pools. When the number of pools grows larger, the gas cost of massUpdatePools() may exceed the maixmum gas limit of a single transaction. In this case, _withUpdate option must be false.

At this point, there are not so many pools so the admin will always set _withUpdate to true when adding a new pool.

**Comment by LiRiu** [comment]
Hummmmmmm i see....
`always set _withUpdate to True` is adequate

One more thing...if you want to update the contract in the future, please fix this potential risk point by the way~
( Just in my opinion, the security of user reward is greater than the gas cost of massUpdatePools()

<img width="119" alt="image" src="https://user-images.githubusercontent.com/103174898/170169851-3e754aae-6045-4246-84c5-8cd3b68568d9.png">

**Comment by posaggen** [comment]
The point is not the gas fee of massUpdatePools() is greater than user reward or not. When the number of pools is too large, the massUpdatePools() will exceed the maximum gas cost of a single transaction then the transaction is invalid and will never be packed in the blockchain.

**Comment by LiRiu** [comment]
确实
